repos:
-   repo: local
    hooks:
    - id: trailing-whitespace
      name: trailing-whitespace
      entry:
    - id: end-of-file-fixer
      name: end-of-file-fixer
    - id: check-added-large-files
      name: check-added-large-files
    - id: poetry-check
      name: poetry-check
    - id: poetry-lock
      name: poetry-lock
    - id: poetry-export
      name: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
