[tool.poetry]
name = "wmp2vec"
version = "0.1.0"
description = ""
authors = ["Morteza Ansarinia <ansarinia@me.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.*"
flake8 = "^4.0.1"
gensim = "^4.1.2"
networkx = "^2.8"
csrgraph = "^0.1.28"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
